#!/usr/local/bin/python3

import cgi
import os

print("HTTP/1.1 200 OK\r")
print("Content-type: text/html\r\n\r")
print ("<html>")
print ("<head><title>CGI Programming</title>")
print ("<style>")
print ("body {")
print ("    font-family: 'Helvetica', sans-serif;")
print ("    background-color: #f5f5f5;")
print ("    margin: 0;")
print ("    padding: 0;")
print ("    display: flex;")
print ("    justify-content: center;")
print ("    align-items: center;")
print ("    min-height: 100vh;")
print ("}")
print ("h1 {")
print ("    text-align: center;")
print ("    color: #333333;")
print ("}")
print (".container {")
print ("    max-width: 400px;")
print ("    background-color: #ffffff;")
print ("    border-radius: 5px;")
print ("    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);")
print ("    padding: 40px;")
print ("}")
print ("label {")
print ("    display: block;")
print ("    font-size: 16px;")
print ("    color: #555555;")
print ("    margin-bottom: 5px;")
print ("}")
print ("input[type='text'] {")
print ("    width: 100%;")
print ("    padding: 12px;")
print ("    font-size: 16px;")
print ("    border: none;")
print ("    background-color: #f2f2f2;")
print ("    border-radius: 5px;")
print ("    margin-bottom: 10px;")
print ("}")
print ("input[type='submit'] {")
print ("    background-color: #007bff;")
print ("    color: #ffffff;")
print ("    cursor: pointer;")
print ("    border: none;")
print ("    padding: 12px 20px;")
print ("    font-size: 16px;")
print ("    border-radius: 5px;")
print ("    transition: background-color 0.3s ease;")
print ("}")
print ("input[type='submit']:hover {")
print ("    background-color: #0056b3;")
print ("}")
print ("</style>")
print ("</head>")
print ("<body>")
print ("<div class='container'>")
print ("<h1>Welcome To Webserv CGI Execution!</h1>")
print ("<h1>Testing Get Method!</h1>")

form = cgi.FieldStorage()

first_name = form.getvalue('first_name')
last_name = form.getvalue('last_name')

if first_name and last_name:
    print ("<h2>First Name: " + first_name + "</h2>")
    print ("<h2>Last Name: " + last_name + "</h2>")
else:
    print ("<h2>No data submitted.</h2>")

print ("</div>")
print ("</body>")
print ("</html>")