#!/usr/local/bin/python3
# Import modules for CGI handling
import cgi

# Create instance of FieldStorage
form = cgi.FieldStorage()

first_name = form.getvalue('first_name')
last_name  = form.getvalue('last_name')

print("HTTP/1.1 200 OK\r")
print("Content-type: text/html\r\n\r")
print ("\r\n")
print ("<html>")
print ("<head>")
print ("<title>Hello py cgi</title>")
print ("<style>")
print ("    body {")
print ("        font-family: Arial, sans-serif;")
print ("        background-color: #f2f2f2;")
print ("        margin: 0;")
print ("        padding: 20px;")
print ("    }")
print ("")
print ("    h1 {")
print ("        color: #333;")
print ("        font-size: 32px;")
print ("        margin-top: 0;")
print ("        text-align: center;")
print ("    }")
print ("")
print ("    p {")
print ("        color: #666;")
print ("        font-size: 18px;")
print ("        margin-top: 20px;")
print ("        text-align: center;")
print ("    }")
print ("</style>")
print ("</head>")
print ("<body>")
print ("<h1>Hello %s%s</h1>" % (first_name, last_name))
print ("</body>")
print ("</html>")